# Generated by Django 4.1.5 on 2023-09-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reciperawmaterial",
            old_name="r_material_name",
            new_name="material_name",
        ),
        migrations.AlterUniqueTogether(
            name="reciperawmaterial",
            unique_together={("recipe", "material_name")},
        ),
    ]
