# Generated by Django 4.2.5 on 2023-09-22 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_rename_r_material_name_reciperawmaterial_material_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeattributelimit',
            name='max_value',
            field=models.DecimalField(decimal_places=2, default=999.9, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Value'),
        ),
        migrations.AlterField(
            model_name='recipeattributelimit',
            name='min_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min Value'),
        ),
    ]
