# Generated by Django 4.1.5 on 2023-09-27 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0004_reciperatios_bestrecipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestrecipe",
            name="material",
            field=models.ForeignKey(
                default=22,
                on_delete=django.db.models.deletion.CASCADE,
                to="ingredients.reciperawmaterial",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bestrecipe",
            name="material_name",
            field=models.CharField(max_length=255),
        ),
    ]
