# Generated by Django 4.1.5 on 2023-09-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0005_bestrecipe_material_alter_bestrecipe_material_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reciperatios",
            unique_together=set(),
        ),
    ]
