# Generated by Django 4.1.5 on 2023-09-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0006_alter_reciperatios_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciperatios",
            name="material_1_name",
            field=models.CharField(default=22, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reciperatios",
            name="material_2_name",
            field=models.CharField(default=22, max_length=255),
            preserve_default=False,
        ),
    ]
