# Generated by Django 4.1.5 on 2023-09-27 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0007_reciperatios_material_1_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reciperatios",
            old_name="material_1_name",
            new_name="nutrition_1_name",
        ),
        migrations.RenameField(
            model_name="reciperatios",
            old_name="material_2_name",
            new_name="nutrition_2_name",
        ),
        migrations.RemoveField(
            model_name="reciperatios",
            name="material_1",
        ),
        migrations.RemoveField(
            model_name="reciperatios",
            name="material_2",
        ),
        migrations.AddField(
            model_name="reciperatios",
            name="nutrition_1",
            field=models.ForeignKey(
                default=22,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrition_1_ratios",
                to="ingredients.recipeattributelimit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reciperatios",
            name="nutrition_2",
            field=models.ForeignKey(
                default=22,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrition_2_ratios",
                to="ingredients.recipeattributelimit",
            ),
            preserve_default=False,
        ),
    ]
