# Generated by Django 4.2.5 on 2023-10-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_recipeattributelimit_max_value_and_more'),
        ('ingredients', '0008_rename_material_1_name_reciperatios_nutrition_1_name_and_more'),
    ]

    operations = [
    ]
