# Generated by Django 4.1.5 on 2023-10-09 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0010_bestrecipenutrition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bestrecipenutrition",
            name="nutrition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ingredients.recipeattributelimit",
            ),
        ),
        migrations.AlterField(
            model_name="bestrecipenutrition",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
