# Generated by Django 4.2.5 on 2023-10-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_merge_20231001_1433'),
        ('ingredients', '0011_alter_bestrecipenutrition_nutrition_and_more'),
    ]

    operations = [
    ]
