# Generated by Django 4.2.5 on 2023-10-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0012_merge_20231011_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tonne',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=99999, verbose_name='Tonne'),
        ),
    ]
